### ISSUE TITLE
邮箱发送失败

### ISSUE THREAD

**Issue by liutf** [xuess/smzdm-sign#1]
* 描述
配置文件中已将密码修改为授权码，报错了。是发送模块没支持授权码登录？

![](http://p2oheco53.bkt.clouddn.com/20180419115020.png)

**Comment by liutf** [comment]
把`mail.js` 这里改为使用`service: 'qq',`就好了。
![](http://p2oheco53.bkt.clouddn.com/20180419141757.png)

**Comment by xuess** [comment]
@liutf  谢谢反馈，还没遇到过这个问题。
