### ISSUE TITLE
现在运行还会有问题嘛

### ISSUE THREAD

**Issue by gutianyi** [xuess/smzdm-sign#12]

**Comment by xuess** [comment]
有段时间没跑这个脚本了，目前在用基于无头浏览器写的脚本在执行，模拟浏览器操作，风险更小点，但是有一定的概率会执行失败，可能跟服务器网络有关系。我整理一下可以发布出来。

**Comment by gutianyi** [comment]
> 有段时间没跑这个脚本了，目前在用基于无头浏览器写的脚本在执行，模拟浏览器操作，风险更小点，但是有一定的概率会执行失败，可能跟服务器网络有关系。我整理一下可以发布出来。

感谢hhh
