### ISSUE TITLE
请问是否可以使用server酱来进行提醒呢

### ISSUE THREAD

**Issue by DocWho22** [xuess/smzdm-sign#13]
您好，邮箱提醒有些麻烦，所以想问下能否选择server酱来进行提醒

**Comment by xuess** [comment]
可以支持

**Comment by xuess** [comment]
> 您好，邮箱提醒有些麻烦，所以想问下能否选择server酱来进行提醒

测试了一下，server酱不支持html发送。内容只能发送markdown格式。
