### ISSUE TITLE
你好，经过测试该脚本可以正常评论3次，但是无法签到。

### ISSUE THREAD

**Issue by SHEN-Cheng** [xuess/smzdm-sign#7]
脚本提示签到完成，但是进入手机客户端和网页版都是未签到状态。
但是进去我的评论的三条都已经评论了，请有空了看一下原因。

**Comment by xuess** [comment]
如果`签到控制台日志`打印了，`网页`上应该是签到的了，但是`客户端`会提醒你再次签到，因为`客户端`签到可以多`+3`积分。

你看一下积分日志，[积分日志地址](https://zhiyou.smzdm.com/user/point/) ，看看是否有 ` 积分：+33经验值：+33连续签到30天以上每天领33积分`，这种信息。

如果有的话，就说明签到成功了。

如果不是此问题，可以把`签到控制台`的日志贴一下，这样好分析些。

**Comment by xuess** [comment]
@shen159876
