### ISSUE TITLE
配置好之后运行出现错误

### ISSUE THREAD

**Issue by zhuzhuani** [xuess/smzdm-sign#8]
你好 发生了如下错误....
![qq 20180814164632](https://user-images.githubusercontent.com/17022713/44081639-c907f87a-9fe1-11e8-83c1-38c11a570f2b.png)

**Comment by xuess** [comment]
@zhuzhuani  你nodejs 什么版本？比较老可能会不兼容ES6语法

**Comment by zhuzhuani** [comment]
你好老哥 我是NODEJS V4版本的

**Comment by zhuzhuani** [comment]
我看有0.10 0.12 V4 V6 V8 我应该选择哪个版本？

**Comment by zhuzhuani** [comment]
老哥 我更新了V8版本之后成功运行了！！！现在去研究下常驻运行！
感谢！

**Comment by zhuzhuani** [comment]
抱歉 现在才看到你的邮件，我在github上看到了你的回复之后更新了nodeJS到V8的版本（之前是V4）
成功运行了这个程序，然后安装了pm2进行常驻运行，目前使用良好，邮件也可以收到，感谢你的程序和教程（不是很懂，，JS应该算脚本吧..）
再次感谢！

午休随笔 <notifications@github.com> 于2018年8月14日周二 下午6:42写道：

**Comment by zhuzhuani** [comment]
我有一个小小的方案：在APP上有个每日任务是评论消息还是阅读文章来着，运行脚本后这个任务就处于完成状态了（但需要点一下领取奖励）不出意外的话应该是一个GET请求，我觉得可以在脚本中加一个跑过脚本之后领取一下奖励的功能，，我不懂手机端抓包，，不知道难易程度，，如果难或者非常麻烦的话，就不需要加了，目前功能已经很完善了！感谢！

**Comment by xuess** [comment]
@zhuzhuani  感谢提议，有时间我去看看，功能能否加进去。
