### ISSUE TITLE
签到时间随机化

### ISSUE THREAD

**Issue by knightyui** [xuess/smzdm-sign#9]
建议将签到和评论时间改成随机的，来自已经被永封账号的痛哈哈。

**Comment by xuess** [comment]
> 建议将签到和评论时间改成随机的，来自已经被永封账号的痛哈哈。

目前就是随机的，只是指定区间随机，具体不知道封号的机制

**Comment by knightyui** [comment]
怀疑封号机制是因为签到时间比较固定且时间较可疑？（之前的区间很小） 我把区间调大了测试一下会不会封号

**Comment by skyox44** [comment]
暂时猜的一些机制：
1.同IP下有多个注册账号（相同的设备信息）
2.同IP下多个账号相同操作
3.被举报
4.无意义留言
5.长时间无手机端登录迹象

**Comment by skyox44** [comment]
签到机制时间好像影响不大。
手动操作每天0点-1点准时签到几个月的账号毫无问题

**Comment by xuess** [comment]
目前用puppeteer 写了个 基于浏览器，一步一步点击的签到，每次都是新设备号，但是IP还是固定的，在自测，目前连续签到十几天了，看会不会被封。

**Comment by knightyui** [comment]
我猜测与签到时间集中关系比较大。我修改为早上五点到下午五点随机签到，目前已经94天，没有被封。

**Comment by xuess** [comment]
基于puppeteer 的签到搞上去，大家可以试试   [https://github.com/xuess/puppeteer-sign](https://github.com/xuess/puppeteer-sign)
